# Florida

In [4]:
import pandas as pd
df = pd.read_csv('/workspaces/pds-2022-turquoise-team/00_source_data/florida_all_data_all_counties.csv')

In [5]:
df

,Unnamed: 0,Deaths,State,County,Year,Population,_merge,Death Rate
0,0,12.0,Alabama,"Autauga County, AL",1999,42963,both,27.931010
1,1,11.0,Alabama,"Autauga County, AL",2000,43671,both,25.188340
2,2,10.0,Alabama,"Autauga County, AL",2001,44889,both,22.277173
3,3,10.0,Alabama,"Autauga County, AL",2002,45909,both,21.782221
4,4,11.0,Alabama,"Autauga County, AL",2001,44889,both,24.504890
...,...,...,...,...,...,...,...,...
72012,72288,5.0,Wyoming,"Weston County, WY",2016,7236,right_only,69.098950
72013,72289,5.0,Wyoming,"Weston County, WY",2017,6927,right_only,72.181319
72014,72290,5.0,Wyoming,"Weston County, WY",2018,6967,right_only,71.766901
72015,72291,5.0,Wyoming,"Weston County, WY",2019,6927,right_only,72.181319
72016,72292,5.0,Wyoming,"Weston County, WY",2020,6743,right_only,74.150971

In [2]:
# FL plot
pre_fl_fit = plotting_chart(
    2010, "blue", fl_policy_pre, "Prescription_Rate", "Year", legend="Florida", alpha=0.05
)
post_fl_fit = plotting_chart(
    2010, "blue", fl_policy_post, "Prescription_Rate", "Year", legend="Florida", alpha=0.05
)
final = pre_fl_fit + post_fl_fit

final.properties(
    title="Pre-Policy VS. Post-Policy of Opioid Regulations on Mortality Rate for Florida"
)

NameError: name 'plotting_chart' is not defined