In [3]:
import pandas as pd
df1 = pd.read_table('/workspaces/pds-2022-turquoise-team/00_source_data/mortality for texas.txt')
df2 = pd.read_csv('/workspaces/pds-2022-turquoise-team/00_source_data/state county population.csv')

In [54]:
df1['Year County Code Combo'] = df1['County Code'].astype(str) + df1['Year'].astype(str)

In [55]:
df2 ['Year County Code Combo'] = df1['County Code'].astype(str) + df1['Year'].astype(str)

In [61]:
to_add_df = df1.merge(df2,indicator = True, on= 'Year County Code Combo', how='outer').loc[lambda x : x['_merge']=='right_only']

In [63]:
df1

,Notes,State,State Code,County,County Code,Year,Year Code,Cause of death,Cause of death Code,Deaths,Population,Crude Rate,Year County Code Combo
0,NaN,Alabama,1.0,"Baldwin County, AL",1003.0,2004.0,2004.0,Accidental poisoning by and exposure to other ...,X44,16.0,156266.0,Unreliable,1003.02004.0
1,NaN,Alabama,1.0,"Baldwin County, AL",1003.0,2005.0,2005.0,Accidental poisoning by and exposure to other ...,X44,10.0,162183.0,Unreliable,1003.02005.0
2,NaN,Alabama,1.0,"Baldwin County, AL",1003.0,2007.0,2007.0,Accidental poisoning by and exposure to other ...,X44,15.0,172404.0,Unreliable,1003.02007.0
3,NaN,Alabama,1.0,"Baldwin County, AL",1003.0,2008.0,2008.0,Accidental poisoning by and exposure to other ...,X44,13.0,175827.0,Unreliable,1003.02008.0
4,NaN,Alabama,1.0,"Baldwin County, AL",1003.0,2009.0,2009.0,Accidental poisoning by and exposure to other ...,X44,20.0,179406.0,11.1479,1003.02009.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4163,2019 data. Underlying and multiple cause of de...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nannan
4164,"unspecified firearm discharge, ICD-10 code X95...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nannan
4165,2020.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nannan
4166,14. Changes to cause of death classification a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nannan
4167,http://wonder.cdc.gov/wonder/help/ucd.html#ICD...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nannan

In [62]:
to_add_df

,Notes,State_x,State Code_x,County_x,County Code_x,Year_x,Year Code_x,Cause of death,Cause of death Code,Deaths,...,Crude Rate,Year County Code Combo,State_y,State Code_y,County_y,County Code_y,Year_y,Year Code_y,Population_y,_merge
19002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,California,6,"Colusa County, CA",6011,1999,1999,18620,right_only
19003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,California,6,"Colusa County, CA",6011,2000,2000,18804,right_only
19004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,California,6,"Colusa County, CA",6011,2001,2001,19022,right_only
19005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,California,6,"Colusa County, CA",6011,2002,2002,19232,right_only
19006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,California,6,"Colusa County, CA",6011,2003,2003,19568,right_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83252,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Wyoming,56,"Weston County, WY",56045,2016,2016,7236,right_only
83253,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Wyoming,56,"Weston County, WY",56045,2017,2017,6927,right_only
83254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Wyoming,56,"Weston County, WY",56045,2018,2018,6967,right_only
83255,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Wyoming,56,"Weston County, WY",56045,2019,2019,6927,right_only
83256,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Wyoming,56,"Weston County, WY",56045,2020,2020,6743,right_only

In [ ]:
import pandas as pd
df = pd.read_csv('/workspaces/pds-2022-turquoise-team/20_intermediate_files/washington_all_counties.csv')
df.drop(['Crude Rate'], axis = 1)

we_want_washington = ['Alaska', 'Hawaii', 'Iowa', 'Kansas', 'Maine', 'Massachusetts',
       'Minnesota', 'Montana', 'Nebraska', 'North Dakota', 'Oregon',
       'South Dakota', 'Virginia', 'Wyoming']
df_washington = df[df['State_y'].isin(we_want_washington)]

df_washington = df_washington.drop(columns = ['State_x', 'County Code_x', 'State Code_x', 'County_x', 'Year_x', 'Population_x'])
df_washington = df_washington[df_washington['Population_y'] != 'Missing']
df_washington['Population_y'] = df_washington['Population_y'].astype('int')


groupedby_df_washington = df_washington.groupby(["Year_y"]).sum() 
groupedby_df_washington = groupedby_df_washington.reset_index(level=None, drop=False, inplace=False, col_level=0, col_fill='')
groupedby_df_washington['Death Rate'] = (groupedby_df_washington['Deaths']/groupedby_df_washington['Population_y'])*100_000

we_want_only_washington = ['Washington']
df_only_washington = df[df['State_y'].isin(we_want_only_washington)]

groupedby_df_only_washington = df_only_washington.groupby(["Year_y"]).sum() 
groupedby_df_only_washington = groupedby_df_only_washington.reset_index(level=None, drop=False, inplace=False, col_level=0, col_fill='')
groupedby_df_only_washington['Death Rate'] = (groupedby_df_only_washington['Deaths']/groupedby_df_only_washington['Population_x'])*100_000


def label_row(row): 
    if row['Year_y'] == 2009:
        return -3
    if row['Year_y'] == 2010: 
        return -2
    if row['Year_y'] == 2011:
        return -1
    if row['Year_y'] == 2012: 
        return 0
    if row['Year_y'] == 2013: 
        return 1
    if row['Year_y'] == 2014: 
        return 2

groupedby_df_only_washington['Years since policy'] = groupedby_df_only_washington.apply (lambda row: label_row(row), axis = 1) 

groupedby_df_washington['Years since policy'] = groupedby_df_washington.apply (lambda row: label_row(row), axis = 1) 


from plotnine import *

g = (
    ggplot(groupedby_df_only_washington, aes(x="Years since policy", y="Death Rate"))
    + geom_smooth(
        method="lm",
        data=groupedby_df_only_washington[groupedby_df_only_washington["Years since policy"] < 0],
        se=False,
    )
    + geom_smooth(
        method="lm",
        data=groupedby_df_only_washington[groupedby_df_only_washington["Years since policy"] >= 0],
        se=False,
    )
    + geom_vline(xintercept=0, linetype="dashed")
    + geom_text(x=-0.7, y=6.1, label="Policy Change", color="black")
    + labs(title="Pre-Post Model Graph, Effective Policy Intervention: Washington")
)
#g.save("images/prepost_successful.pdf")
print(g)



groupedby_df_only_washington['Policy or Control'] = 'Policy'
groupedby_df_washington['Policy or Control'] = 'Control'

washington_policy_control = pd.concat([groupedby_df_washington, groupedby_df_only_washington])

h = (
    ggplot(
        washington_policy_control,
        aes(x="Years since policy", y="Death Rate", color="Policy or Control"),
    )
    + geom_smooth(
        method="lm", data=washington_policy_control[washington_policy_control["Years since policy"] < 0]
    )
    + geom_smooth(
        method="lm", data=washington_policy_control[washington_policy_control["Years since policy"] >= 0]
    )
    + geom_vline(xintercept=0, linetype="dashed")
    + geom_text(x=-0.7, y=7, label="Policy or Control", color="black")
    + labs(
        title="Diff-in-Diff Model Graph, Effective Policy Intervention: Washington",
        color="Counties in State with Policy Change",
    )
    + theme(legend_position="bottom")
)
#g.save("images/diffindiff_successful.pdf")
print(h)

In [6]:
import pandas as pd
df = pd.read_csv('/workspaces/pds-2022-turquoise-team/20_intermediate_files/washington_all_counties.csv')
df.drop(['Crude Rate'], axis = 1)

/tmp/ipykernel_31076/4214276010.py:2: DtypeWarning: Columns (1,3,6,7,10,11,12,20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/workspaces/pds-2022-turquoise-team/20_intermediate_files/washington_all_counties.csv')

,Unnamed: 0,State_x,State Code_x,County_x,County Code_x,Year_x,Cause of death,Cause of death Code,Deaths,Population_x,State_Code,County Name,year code combo,State_y,State Code_y,County_y,County Code_y,Year_y,Year Code,Population_y
0,241.0,Arkansas,5.0,"Benton County, AR",5007.0,2009.0,Accidental poisoning by and exposure to other ...,X44,12.0,216620.0,AR,Benton County,7016.0,Arkansas,5,"Arkansas County, AR",5001,2015,2015,18433
1,241.0,Arkansas,5.0,"Benton County, AR",5007.0,2009.0,Accidental poisoning by and exposure to other ...,X44,12.0,216620.0,AR,Benton County,7016.0,Arkansas,5,"Ashley County, AR",5003,2013,2013,21283
2,241.0,Arkansas,5.0,"Benton County, AR",5007.0,2009.0,Accidental poisoning by and exposure to other ...,X44,12.0,216620.0,AR,Benton County,7016.0,Arkansas,5,"Baxter County, AR",5005,2011,2011,41536
3,241.0,Arkansas,5.0,"Benton County, AR",5007.0,2009.0,Accidental poisoning by and exposure to other ...,X44,12.0,216620.0,AR,Benton County,7016.0,Arkansas,5,"Benton County, AR",5007,2009,2009,216620
4,241.0,Arkansas,5.0,"Benton County, AR",5007.0,2009.0,Accidental poisoning by and exposure to other ...,X44,12.0,216620.0,AR,Benton County,7016.0,Arkansas,5,"Boone County, AR",5009,2007,2007,36759
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83121,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,58062.0,Wyoming,56,"Weston County, WY",56045,2017,2017,6927
83122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,58063.0,Wyoming,56,"Washakie County, WY",56043,2020,2020,7760
83123,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,58063.0,Wyoming,56,"Weston County, WY",56045,2018,2018,6967
83124,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,58064.0,Wyoming,56,"Weston County, WY",56045,2019,2019,6927
83125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,58065.0,Wyoming,56,"Weston County, WY",56045,2020,2020,6743

In [7]:
we_want_washington = ['Alaska', 'Hawaii', 'Iowa', 'Kansas', 'Maine', 'Massachusetts',
       'Minnesota', 'Montana', 'Nebraska', 'North Dakota', 'Oregon',
       'South Dakota', 'Virginia', 'Wyoming']
df_washington = df[df['State_y'].isin(we_want_washington)]

In [8]:
df_washington = df_washington.drop(columns = ['State_x', 'County Code_x', 'State Code_x', 'County_x', 'Year_x', 'Population_x'])
df_washington = df_washington[df_washington['Population_y'] != 'Missing']
df_washington['Population_y'] = df_washington['Population_y'].astype('int')

In [9]:
df_washington

,Unnamed: 0,Cause of death,Cause of death Code,Deaths,Crude Rate,State_Code,County Name,year code combo,State_y,State Code_y,County_y,County Code_y,Year_y,Year Code,Population_y
11606,1565.0,Poisoning by and exposure to other and unspeci...,Y14,14.0,Unreliable,HI,Hawaii County,17010.0,Hawaii,15,"Hawaii County, HI",15001,2009,2009,183629
11607,1565.0,Poisoning by and exposure to other and unspeci...,Y14,14.0,Unreliable,HI,Hawaii County,17010.0,Hawaii,15,"Honolulu County, HI",15003,2007,2007,925335
11608,1565.0,Poisoning by and exposure to other and unspeci...,Y14,14.0,Unreliable,HI,Hawaii County,17010.0,Hawaii,15,"Kauai County, HI",15007,2003,2003,60805
11609,1565.0,Poisoning by and exposure to other and unspeci...,Y14,14.0,Unreliable,HI,Hawaii County,17010.0,Hawaii,15,"Maui County, HI",15009,2001,2001,132290
11610,1566.0,Poisoning by and exposure to other and unspeci...,Y14,10.0,Unreliable,HI,Hawaii County,17011.0,Hawaii,15,"Hawaii County, HI",15001,2010,2010,185079
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83121,NaN,NaN,NaN,5.0,NaN,NaN,NaN,58062.0,Wyoming,56,"Weston County, WY",56045,2017,2017,6927
83122,NaN,NaN,NaN,5.0,NaN,NaN,NaN,58063.0,Wyoming,56,"Washakie County, WY",56043,2020,2020,7760
83123,NaN,NaN,NaN,5.0,NaN,NaN,NaN,58063.0,Wyoming,56,"Weston County, WY",56045,2018,2018,6967
83124,NaN,NaN,NaN,5.0,NaN,NaN,NaN,58064.0,Wyoming,56,"Weston County, WY",56045,2019,2019,6927
83125,NaN,NaN,NaN,5.0,NaN,NaN,NaN,58065.0,Wyoming,56,"Weston County, WY",56045,2020,2020,6743

In [30]:

df_washington['groupedbykey'] = df_washington['Year_y'].astype('str')+ ',' + df_washington['County Name'] + ',' + df_washington['State_y']

In [31]:
groupedby_df_washington = df_washington.groupby(["groupedbykey"]).sum()

/tmp/ipykernel_31076/1791956209.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  groupedby_df_washington = df_washington.groupby(["groupedbykey"]).sum()

In [44]:
grouped_by_df_washington = groupedby_df_washington.reset_index(level=None, drop=False, inplace=False, col_level=0, col_fill='')

In [47]:
grouped_by_df_washington

,groupedbykey,Unnamed: 0,Deaths,year code combo,State Code_y,County Code_y,Year_y,Year Code,Population_y
0,"1999,Anoka County,Minnesota",10645.0,68.0,116058.0,108,108062,7996,7996,145854
1,"1999,Barnstable County,Massachusetts",9239.0,67.0,108050.0,100,100054,7996,7996,830353
2,"1999,Berkshire County,Massachusetts",4632.0,26.0,54028.0,50,50030,3998,3998,1915188
3,"1999,Bristol County,Massachusetts",23259.0,316.0,270160.0,250,250170,19990,19990,6322095
4,"1999,Chesterfield County,Virginia",9814.0,27.0,106102.0,102,102104,3998,3998,40982
...,...,...,...,...,...,...,...,...,...
1005,"2020,Washington County,Minnesota",2709.0,14.0,29177.0,27,27157,2020,2020,21642
1006,"2020,Washington County,Oregon",23724.0,78.0,258476.0,246,246356,12120,12120,313800
1007,"2020,Worcester County,Massachusetts",12200.0,284.0,135195.0,125,125095,10100,10100,4648952
1008,"2020,Wyandotte County,Kansas",3910.0,22.0,44440.0,40,40400,4040,4040,6963
1009,"2020,York County,Maine",6602.0,43.0,75133.0,69,69073,6060,6060,137314

In [51]:
grouped_by_df_washington[['Year', 'County','State']]= grouped_by_df_washington['groupedbykey'].str.split(pat=",", n=-1, expand=True)

In [52]:
grouped_by_df_washington

,groupedbykey,Unnamed: 0,Deaths,year code combo,State Code_y,County Code_y,Year_y,Year Code,Population_y,Year,County,State
0,"1999,Anoka County,Minnesota",10645.0,68.0,116058.0,108,108062,7996,7996,145854,1999,Anoka County,Minnesota
1,"1999,Barnstable County,Massachusetts",9239.0,67.0,108050.0,100,100054,7996,7996,830353,1999,Barnstable County,Massachusetts
2,"1999,Berkshire County,Massachusetts",4632.0,26.0,54028.0,50,50030,3998,3998,1915188,1999,Berkshire County,Massachusetts
3,"1999,Bristol County,Massachusetts",23259.0,316.0,270160.0,250,250170,19990,19990,6322095,1999,Bristol County,Massachusetts
4,"1999,Chesterfield County,Virginia",9814.0,27.0,106102.0,102,102104,3998,3998,40982,1999,Chesterfield County,Virginia
...,...,...,...,...,...,...,...,...,...,...,...,...
1005,"2020,Washington County,Minnesota",2709.0,14.0,29177.0,27,27157,2020,2020,21642,2020,Washington County,Minnesota
1006,"2020,Washington County,Oregon",23724.0,78.0,258476.0,246,246356,12120,12120,313800,2020,Washington County,Oregon
1007,"2020,Worcester County,Massachusetts",12200.0,284.0,135195.0,125,125095,10100,10100,4648952,2020,Worcester County,Massachusetts
1008,"2020,Wyandotte County,Kansas",3910.0,22.0,44440.0,40,40400,4040,4040,6963,2020,Wyandotte County,Kansas
1009,"2020,York County,Maine",6602.0,43.0,75133.0,69,69073,6060,6060,137314,2020,York County,Maine

In [ ]:
groupedby_df_washington = df_washington.groupby(["Year_y"], ["County_y"]).sum() 
groupedby_df_washington = groupedby_df_washington.reset_index(level=None, drop=False, inplace=False, col_level=0, col_fill='')
groupedby_df_washington['Death Rate'] = (groupedby_df_washington['Deaths']/groupedby_df_washington['Population_y'])*100_000

In [53]:
grouped_by_df_washington['year code combo'].value_counts()

87442.0     11
129123.0    11
63526.0     11
155286.0    11
22186.0     11
            ..
22219.0      1
54074.0      1
135179.0     1
136120.0     1
189153.0     1
Name: year code combo, Length: 197, dtype: int64